export const fakeData = [
  {
    id: 15,
    fullName: 'Nguyễn Chiến',
    applicationPosition: 'Kỹ sư phần mềm',
    email: 'chiennguyen2002@gmail.com',
    phone: '0912345678',
    gender: 'NAM',
    dateOB: '2002-05-14',
    city: 'Hà Nội',
    address: '123 Phạm Văn Đồng, Hà Nội',
    linkedIn: 'linkedin.com/in/chiennguyen',
    github: 'github.com/chiennguyen',
    aboutYourself: 'Tôi là một kỹ sư phần mềm đam mê với sự quan tâm mạnh mẽ vào phát triển backend và kỹ thuật dữ liệu. Tôi thích giải quyết các vấn đề phức tạp và luôn học hỏi các công nghệ mới.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Công ty ABC',
        startWorkingTime: '2022-01-01',
        endWorkingTime: '2022-06-30',
        position: 'Thực tập sinh',
        jobDetail: 'Phát triển các API RESTful và dịch vụ microservices bằng Java và framework Spring Boot. Làm việc trên thiết kế và tối ưu hóa cơ sở dữ liệu.',
        technology: 'Java, Spring Boot, MySQL',
      },
      {
        id: 2,
        companyName: 'Công ty XYZ',
        startWorkingTime: '2021-06-01',
        endWorkingTime: '2021-12-31',
        position: 'Thực tập sinh phát triển phần mềm',
        jobDetail: 'Đóng góp vào việc phát triển một ứng dụng web cho quản lý hàng tồn kho. Thực hiện các tính năng frontend bằng React và dịch vụ backend bằng Node.js và Express.',
        technology: 'React, Node.js, Express',
      },
    ],
    mainSkill: 'Java, Spring Boot, SQL',
    skills: 'Phát triển Backend, API RESTful, Thiết kế Cơ sở dữ liệu, Giải quyết vấn đề',
    school: 'Trường Đại học Công nghệ, Hà Nội',
    startEdudatiomTime: '2020-09-01',
    endEducationTime: '2024-06-30',
    major: 'Khoa học Máy tính',
    others: 'Người chiến thắng cuộc thi lập trình của trường Đại học vào năm 2021.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Website Thương mại điện tử',
        startTime: '2021-03-01',
        endTime: '2021-05-30',
        client: 'Công ty ABC',
        description: 'Phát triển một trang web thương mại điện tử hoàn chỉnh với chức năng xác thực người dùng, duyệt sản phẩm và thanh toán.',
        members: 'Nhóm 4 nhà phát triển',
        position: 'Phát triển Backend',
        responsibilities: 'Thiết kế và triển khai các dịch vụ backend, tích hợp cổng thanh toán và tối ưu hóa truy vấn cơ sở dữ liệu.',
        technology: 'Java, Spring Boot, MySQL',
      },
      {
        id: 2,
        nameProject: 'Hệ thống Quản lý Hàng tồn kho',
        startTime: '2022-02-01',
        endTime: '2022-04-30',
        client: 'Công ty XYZ',
        description: 'Xây dựng một hệ thống quản lý hàng tồn kho dựa trên web để tối ưu hóa quy trình theo dõi hàng tồn kho của khách hàng.',
        members: 'Nhóm 3 nhà phát triển',
        position: 'Phát triển phần mềm',
        responsibilities: 'Phát triển các thành phần frontend, triển khai logic backend và thực hiện kiểm thử hệ thống.',
        technology: 'React, Node.js, Express, MongoDB',
      },
    ],
  },
  {
    id: 15,
    fullName: 'Hoàng Trần',
    applicationPosition: 'Lập trình viên tự do',
    email: 'hoangtran2003@gmail.com',
    phone: '0987654321',
    gender: 'MALE',
    dateOB: '2003-08-22',
    city: 'Đà Nẵng',
    address: '456 Lê Duẩn, Đà Nẵng',
    linkedIn: 'linkedin.com/in/hoangtran',
    github: 'github.com/hoangtran',
    aboutYourself: 'Tôi là một nhà phát triển web sáng tạo và tâm huyết. Với niềm đam mê về thiết kế và chi tiết, tôi luôn nỗ lực để tạo ra các sản phẩm web chất lượng cao và thú vị.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Công ty ABC',
        startWorkingTime: '2021-01-01',
        endWorkingTime: '2021-06-30',
        position: 'Thực tập sinh',
        jobDetail: 'Phát triển các trang web và ứng dụng web sử dụng HTML, CSS và JavaScript. Tương tác với các khách hàng để hiểu và triển khai các yêu cầu dự án.',
        technology: 'HTML, CSS, JavaScript',
      },
      {
        id: 2,
        companyName: 'Công ty XYZ',
        startWorkingTime: '2020-06-01',
        endWorkingTime: '2020-12-31',
        position: 'Thực tập sinh phát triển phần mềm',
        jobDetail: 'Tham gia vào việc phát triển một ứng dụng web đa nền tảng sử dụng React và Node.js. Thực hiện kiểm thử và sửa lỗi cho ứng dụng.',
        technology: 'React, Node.js, Express',
      },
    ],
    mainSkill: 'HTML, CSS, JavaScript',
    skills: 'Thiết kế web, Phát triển front-end, Hiểu biết về UX/UI',
    school: 'Trường Đại học Công nghệ, Đà Nẵng',
    startEdudatiomTime: '2019-09-01',
    endEducationTime: '2023-06-30',
    major: 'Khoa học Máy tính',
    others: 'Tham gia các hoạt động ngoại khóa liên quan đến lập trình và thiết kế web.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Website Thương mại điện tử',
        startTime: '2022-01-01',
        endTime: '2022-05-30',
        client: 'Công ty ABC',
        description: 'Phát triển một trang web thương mại điện tử đẹp mắt và dễ sử dụng cho khách hàng. Tích hợp hệ thống thanh toán trực tuyến an toàn và đáng tin cậy.',
        members: 'Nhóm 4 nhà phát triển',
        position: 'Phát triển Front-end',
        responsibilities: 'Thiết kế giao diện người dùng và triển khai các tính năng front-end. Tương tác chặt chẽ với backend để đảm bảo tính liên kết và hiệu suất của trang web.',
        technology: 'HTML, CSS, JavaScript',
      },
      {
        id: 2,
        nameProject: 'Ứng dụng Quản lý Sự kiện',
        startTime: '2021-03-01',
        endTime: '2021-06-30',
        client: 'Công ty XYZ',
        description: 'Xây dựng một ứng dụng web đa nền tảng để quản lý và tổ chức sự kiện. Cung cấp giao diện dễ sử dụng và tính năng đa dạng cho người dùng.',
        members: 'Nhóm 3 nhà phát triển',
        position: 'Phát triển Front-end',
        responsibilities: 'Thiết kế và triển khai giao diện người dùng. Tương tác với backend để lấy và xử lý dữ liệu từ cơ sở dữ liệu.',
        technology: 'React, Node.js, MongoDB',
      },
    ],
  },
  {
    id: 15,
    fullName: 'Minh Phạm',
    applicationPosition: 'Thực tập sinh tại XYZ Corp',
    email: 'minhpham2001@gmail.com',
    phone: '0923456789',
    gender: 'MALE',
    dateOB: '2001-11-30',
    city: 'Thành phố Hồ Chí Minh',
    address: '789 Trần Hưng Đạo, Thành phố Hồ Chí Minh',
    linkedIn: null,
    github: null,
    aboutYourself: 'Tôi là một nhà khoa học dữ liệu tương lai với kỹ năng phân tích mạnh mẽ và đam mê quyết định dựa trên dữ liệu.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'XYZ Corp',
        startWorkingTime: '2023-01-01',
        endWorkingTime: '2023-06-30',
        position: 'Thực tập sinh',
        jobDetail: 'Thực hiện các dự án phân tích dữ liệu, xử lý và trực quan hóa dữ liệu sử dụng Python và các thư viện phổ biến như Pandas và Matplotlib.',
        technology: 'Python, Pandas, Matplotlib',
      },
    ],
    mainSkill: 'Python, Phân tích dữ liệu, Học máy',
    skills: 'Python programming, Data Analysis, Machine Learning',
    school: 'Đại học Bách Khoa, Thành phố Hồ Chí Minh',
    startEdudatiomTime: '2019-09-01',
    endEducationTime: '2023-06-30',
    major: 'Khoa học Dữ liệu',
    others: 'Đạt giải Nhất cuộc thi Phân tích Dữ liệu Trẻ năm 2022.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Phân tích Dữ liệu Thị trường Chứng khoán',
        startTime: '2022-03-01',
        endTime: '2022-05-30',
        client: 'Trường Đại học',
        description: 'Thực hiện phân tích dữ liệu thị trường chứng khoán, dự đoán giá cổ phiếu sử dụng các mô hình học máy và kỹ thuật xử lý dữ liệu.',
        members: 'Nhóm 3 sinh viên',
        position: 'Lập trình viên, Nhà phân tích dữ liệu',
        responsibilities: 'Thu thập dữ liệu, xây dựng và huấn luyện mô hình, đánh giá và tối ưu hóa kết quả.',
        technology: 'Python, Scikit-learn, TensorFlow',
      },
      {
        id: 2,
        nameProject: 'Dự đoán Tình trạng Giao thông',
        startTime: '2021-08-01',
        endTime: '2021-10-31',
        client: 'Thành phố Hồ Chí Minh',
        description: 'Phân tích dữ liệu giao thông thành phố, dự đoán tình trạng giao thông tại các điểm nút giao thông sử dụng mạng nơ-ron học sâu.',
        members: 'Nhóm 4 sinh viên',
        position: 'Lập trình viên, Nhà phân tích dữ liệu',
        responsibilities: 'Xử lý và tiền xử lý dữ liệu, xây dựng mô hình dự đoán, triển khai và đánh giá kết quả.',
        technology: 'Python, TensorFlow, Keras',
      },
    ],
  },
  {
    id: 16,
    fullName: 'Thúy Lê',
    applicationPosition: 'Thực tập sinh thiết kế đồ họa tại Creative Studio',
    email: 'thuyle2004@gmail.com',
    phone: '0934567890',
    gender: 'FEMALE',
    dateOB: '2004-03-12',
    city: 'Huế',
    address: '321 Nguyễn Huệ, Huế',
    linkedIn: null,
    github: null,
    aboutYourself: 'Tôi là một nhà thiết kế đồ họa tài năng với đam mê kể chuyện bằng hình ảnh và xây dựng thương hiệu.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Creative Studio',
        startWorkingTime: '2023-01-01',
        endWorkingTime: '2023-06-30',
        position: 'Thực tập sinh thiết kế đồ họa',
        jobDetail: 'Thực hiện các dự án thiết kế đồ họa cho khách hàng, bao gồm thiết kế logo, banner, và tài liệu marketing.',
        technology: 'Photoshop, Illustrator, InDesign',
      },
    ],
    mainSkill: 'Thiết kế đồ họa, Photoshop, Illustrator',
    skills: 'Graphic Design, Photoshop, Illustrator, InDesign',
    school: 'Đại học Nghệ thuật, Huế',
    startEdudatiomTime: '2021-09-01',
    endEducationTime: '2025-06-30',
    major: 'Thiết kế đồ họa',
    others: 'Đạt giải Nhì cuộc thi Thiết kế Poster năm 2022.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Thiết kế Logo cho Công ty ABC',
        startTime: '2022-04-01',
        endTime: '2022-05-15',
        client: 'Công ty ABC',
        description: 'Thiết kế logo mới cho Công ty ABC, giúp họ xây dựng thương hiệu mạnh mẽ và dễ nhận diện.',
        members: 'Nhóm 2 nhà thiết kế',
        position: 'Nhà thiết kế đồ họa',
        responsibilities: 'Phác thảo ý tưởng, tạo mẫu thiết kế và chỉnh sửa theo yêu cầu của khách hàng.',
        technology: 'Photoshop, Illustrator',
      },
      {
        id: 2,
        nameProject: 'Thiết kế Banner Quảng cáo cho Sự kiện XYZ',
        startTime: '2023-03-01',
        endTime: '2023-03-30',
        client: 'Sự kiện XYZ',
        description: 'Thiết kế banner quảng cáo cho sự kiện XYZ, thu hút sự chú ý của khách hàng và tăng cường hiệu quả quảng bá.',
        members: 'Nhóm 3 nhà thiết kế',
        position: 'Nhà thiết kế đồ họa',
        responsibilities: 'Tạo và chỉnh sửa thiết kế banner theo yêu cầu của sự kiện, đảm bảo tính thẩm mỹ và thu hút.',
        technology: 'Photoshop, Illustrator',
      },
    ],
  },
  {
    id: 17,
    fullName: 'Tuấn Nguyễn',
    applicationPosition: 'Thực tập sinh hệ thống nhúng tại SmartTech',
    email: 'tuannguyen2000@gmail.com',
    phone: '0945678901',
    gender: 'MALE',
    dateOB: '2000-07-19',
    city: 'Cần Thơ',
    address: '654 Nguyễn Văn Cừ, Cần Thơ',
    linkedIn: null,
    github: null,
    aboutYourself: 'Tôi đam mê về IoT và hệ thống nhúng, với nền tảng vững chắc về lập trình C++.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'SmartTech',
        startWorkingTime: '2023-01-01',
        endWorkingTime: '2023-06-30',
        position: 'Thực tập sinh hệ thống nhúng',
        jobDetail: 'Phát triển và kiểm thử các hệ thống nhúng, làm việc với các dự án IoT sử dụng C++ và các bộ vi xử lý.',
        technology: 'C++, ARM Cortex, FreeRTOS',
      },
    ],
    mainSkill: 'C++, Hệ thống nhúng, IoT',
    skills: 'Embedded Systems, IoT Development, C++ Programming',
    school: 'Đại học Cần Thơ',
    startEdudatiomTime: '2018-09-01',
    endEducationTime: '2022-06-30',
    major: 'Kỹ thuật Điện tử',
    others: 'Đạt giải Ba cuộc thi IoT Quốc gia năm 2021.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Hệ thống Giám sát Nhiệt độ và Độ Ẩm',
        startTime: '2022-03-01',
        endTime: '2022-05-30',
        client: 'Công ty ABC',
        description: 'Phát triển hệ thống IoT để giám sát nhiệt độ và độ ẩm trong các kho hàng, bao gồm cả phần cứng và phần mềm.',
        members: 'Nhóm 4 kỹ sư',
        position: 'Kỹ sư hệ thống nhúng',
        responsibilities: 'Thiết kế và phát triển phần mềm nhúng, tích hợp cảm biến và kiểm thử hệ thống.',
        technology: 'C++, ARM Cortex, FreeRTOS',
      },
      {
        id: 2,
        nameProject: 'Hệ thống Điều khiển Nhà Thông minh',
        startTime: '2021-08-01',
        endTime: '2021-10-31',
        client: 'SmartHome Inc.',
        description: 'Xây dựng hệ thống điều khiển nhà thông minh sử dụng IoT, cho phép người dùng điều khiển các thiết bị điện tử trong nhà qua ứng dụng di động.',
        members: 'Nhóm 5 kỹ sư',
        position: 'Kỹ sư hệ thống nhúng',
        responsibilities: 'Phát triển và kiểm thử các mô-đun phần mềm, tích hợp với các thiết bị IoT và đảm bảo tính bảo mật.',
        technology: 'C++, MQTT, FreeRTOS',
      },
    ],
  },
  {
    id: 18,
    fullName: 'Anh Đào',
    applicationPosition: 'Thực tập sinh marketing tại Digital Agency',
    email: 'anhdao2005@gmail.com',
    phone: '0956789012',
    gender: 'FEMALE',
    dateOB: '2005-09-05',
    city: 'Hải Phòng',
    address: '987 Bà Triệu, Hải Phòng',
    linkedIn: null,
    github: null,
    aboutYourself: 'Tôi là một chuyên viên marketing số tận tâm với khả năng tạo nội dung hấp dẫn và cải thiện sự hiện diện trực tuyến.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Digital Agency',
        startWorkingTime: '2023-01-01',
        endWorkingTime: '2023-06-30',
        position: 'Thực tập sinh marketing',
        jobDetail: 'Hỗ trợ triển khai các chiến dịch marketing số, tối ưu hóa SEO và tạo nội dung cho các kênh truyền thông xã hội.',
        technology: 'Google Analytics, Ahrefs, Canva',
      },
    ],
    mainSkill: 'Marketing số, SEO, Tạo nội dung',
    skills: 'Digital Marketing, SEO, Content Creation, Social Media Management',
    school: 'Đại học Hải Phòng',
    startEdudatiomTime: '2023-09-01',
    endEducationTime: '2027-06-30',
    major: 'Marketing',
    others: 'Đạt giải Nhất cuộc thi Tạo Nội dung Sáng tạo của trường năm 2022.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Chiến dịch Tăng Tương Tác Trực Tuyến',
        startTime: '2022-03-01',
        endTime: '2022-05-30',
        client: 'Công ty XYZ',
        description: 'Triển khai chiến dịch marketing để tăng tương tác trực tuyến và cải thiện sự hiện diện của thương hiệu trên các nền tảng xã hội.',
        members: 'Nhóm 3 chuyên viên marketing',
        position: 'Thực tập sinh marketing',
        responsibilities: 'Tạo nội dung, quản lý các kênh truyền thông xã hội và theo dõi kết quả chiến dịch.',
        technology: 'Google Analytics, Ahrefs, Canva',
      },
      {
        id: 2,
        nameProject: 'Chiến dịch SEO cho Trang Web Công ty',
        startTime: '2023-02-01',
        endTime: '2023-04-30',
        client: 'Công ty ABC',
        description: 'Tối ưu hóa SEO cho trang web công ty để tăng lưu lượng truy cập và cải thiện thứ hạng trên công cụ tìm kiếm.',
        members: 'Nhóm 4 chuyên viên marketing',
        position: 'Thực tập sinh marketing',
        responsibilities: 'Nghiên cứu từ khóa, tạo nội dung SEO và phân tích dữ liệu hiệu suất.',
        technology: 'Google Analytics, Ahrefs, WordPress',
      },
    ],
  },
  {
    id: 19,
    fullName: 'Sơn Vũ',
    applicationPosition: 'Thực tập sinh an ninh mạng tại SecureTech',
    email: 'sonvu2002@gmail.com',
    phone: '0967890123',
    gender: 'MALE',
    dateOB: '2002-02-28',
    city: 'Hà Nội',
    address: '123 Nguyễn Thái Học, Hà Nội',
    linkedIn: null,
    github: 'github.com/sonvu',
    aboutYourself: 'Tôi là một người đam mê an ninh mạng với nền tảng vững chắc về bảo mật mạng và hack đạo đức.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'SecureTech',
        startWorkingTime: '2023-01-01',
        endWorkingTime: '2023-06-30',
        position: 'Thực tập sinh an ninh mạng',
        jobDetail: 'Tham gia vào việc kiểm tra bảo mật hệ thống, phát hiện và khắc phục lỗ hổng bảo mật, và thực hiện các bài kiểm tra xâm nhập.',
        technology: 'Python, Kali Linux, Wireshark',
      },
    ],
    mainSkill: 'Bảo mật mạng, Linux, Python',
    skills: 'Network Security, Ethical Hacking, Linux Administration, Python Scripting',
    school: 'Đại học Bách Khoa Hà Nội',
    startEdudatiomTime: '2020-09-01',
    endEducationTime: '2024-06-30',
    major: 'An ninh mạng',
    others: 'Đạt chứng chỉ CEH (Certified Ethical Hacker) năm 2023.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Kiểm tra bảo mật hệ thống',
        startTime: '2022-03-01',
        endTime: '2022-05-30',
        client: 'Công ty XYZ',
        description: 'Thực hiện kiểm tra bảo mật cho hệ thống của khách hàng, bao gồm phân tích lỗ hổng và đề xuất biện pháp khắc phục.',
        members: 'Nhóm 3 chuyên viên an ninh mạng',
        position: 'Thực tập sinh an ninh mạng',
        responsibilities: 'Phân tích lỗ hổng, thực hiện kiểm tra xâm nhập và báo cáo kết quả.',
        technology: 'Python, Kali Linux, Nessus',
      },
      {
        id: 2,
        nameProject: 'Phát triển công cụ kiểm tra bảo mật',
        startTime: '2023-02-01',
        endTime: '2023-04-30',
        client: 'SecureTech',
        description: 'Phát triển một công cụ kiểm tra bảo mật tự động để giúp phát hiện lỗ hổng bảo mật nhanh chóng và hiệu quả.',
        members: 'Nhóm 4 chuyên viên an ninh mạng',
        position: 'Thực tập sinh an ninh mạng',
        responsibilities: 'Lập trình công cụ, kiểm thử và tối ưu hóa.',
        technology: 'Python, Bash, Docker',
      },
    ],
  },
  {
    id: 20,
    fullName: 'Lâm Trần',
    applicationPosition: 'Junior Mobile Dev',
    email: 'lamtran2003@gmail.com',
    phone: '0978901234',
    gender: 'MALE',
    dateOB: '2003-10-16',
    city: 'Đà Nẵng',
    address: '456 Lê Lợi, Đà Nẵng',
    linkedIn: 'linkedin.com/in/lamtran',
    github: 'github.com/lamtran',
    aboutYourself: 'Đam mê phát triển ứng dụng di động, với kinh nghiệm trong cả nền tảng Android và iOS.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'AppDev',
        startWorkingTime: '2023-01-01',
        endWorkingTime: '2023-06-30',
        position: 'Thực tập sinh phát triển di động',
        jobDetail: 'Phát triển và tối ưu hóa các ứng dụng di động trên cả hai nền tảng Android và iOS bằng Kotlin và Flutter. Hỗ trợ đội ngũ phát triển trong việc kiểm tra và sửa lỗi ứng dụng.',
        technology: 'Kotlin, Flutter, Dart',
      },
    ],
    mainSkill: 'Phát triển di động, Kotlin, Flutter',
    skills: 'Mobile App Development, Android Development, iOS Development, Dart Programming',
    school: 'Đại học Bách Khoa Đà Nẵng',
    startEdudatiomTime: '2021-09-01',
    endEducationTime: '2025-06-30',
    major: 'Khoa học Máy tính',
    others: 'Tham gia cuộc thi phát triển ứng dụng di động và đạt giải nhất năm 2022.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Ứng dụng Quản lý Công việc',
        startTime: '2022-03-01',
        endTime: '2022-05-30',
        client: 'Công ty XYZ',
        description: 'Phát triển ứng dụng quản lý công việc cho doanh nghiệp, giúp quản lý và phân công công việc hiệu quả.',
        members: 'Nhóm 5 nhà phát triển',
        position: 'Phát triển di động',
        responsibilities: 'Phát triển các tính năng chính của ứng dụng, kiểm tra và sửa lỗi.',
        technology: 'Kotlin, Flutter, Firebase',
      },
      {
        id: 2,
        nameProject: 'Ứng dụng Giao thông Thông minh',
        startTime: '2023-02-01',
        endTime: '2023-04-30',
        client: 'Công ty ABC',
        description: 'Phát triển ứng dụng giao thông thông minh giúp người dùng tìm kiếm lộ trình di chuyển tối ưu và thông tin giao thông thời gian thực.',
        members: 'Nhóm 4 nhà phát triển',
        position: 'Phát triển di động',
        responsibilities: 'Thiết kế và triển khai giao diện người dùng, tích hợp API giao thông.',
        technology: 'Kotlin, Flutter, Google Maps API',
      },
    ],
  },
  {
    id: 21,
    fullName: 'Hạnh Nguyễn',
    applicationPosition: 'Thực tập sinh quản lý dự án tại IT Solutions',
    email: 'hanhnguyen2001@gmail.com',
    phone: '0989012345',
    gender: 'FEMALE',
    dateOB: '2001-01-20',
    city: 'Vũng Tàu',
    address: '789 Phan Chu Trinh, Vũng Tàu',
    linkedIn: 'linkedin.com/in/hanhnguyen',
    github: 'github.com/hanhnguyen',
    aboutYourself: 'Quản lý dự án có tổ chức và chi tiết với kinh nghiệm trong các phương pháp Agile và Scrum.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'IT Solutions',
        startWorkingTime: '2022-01-01',
        endWorkingTime: '2022-06-30',
        position: 'Thực tập sinh quản lý dự án',
        jobDetail: 'Hỗ trợ quản lý các dự án phần mềm, theo dõi tiến độ dự án và điều phối công việc theo phương pháp Agile và Scrum. Tham gia các cuộc họp Sprint Planning và Sprint Review.',
        technology: 'Jira, Confluence, MS Project',
      },
    ],
    mainSkill: 'Quản lý dự án, Agile, Scrum',
    skills: 'Project Management, Agile Methodologies, Scrum, Time Management, Communication',
    school: 'Đại học Kinh tế - Tài chính TP.HCM',
    startEdudatiomTime: '2019-09-01',
    endEducationTime: '2023-06-30',
    major: 'Quản trị Kinh doanh',
    others: 'Tham gia khóa học Quản lý dự án chuyên nghiệp (PMP) và đạt chứng chỉ vào năm 2021.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Hệ thống Quản lý Khách hàng (CRM)',
        startTime: '2021-02-01',
        endTime: '2021-04-30',
        client: 'Công ty ABC',
        description: 'Triển khai hệ thống quản lý khách hàng giúp nâng cao hiệu quả quản lý và chăm sóc khách hàng.',
        members: 'Nhóm 6 thành viên',
        position: 'Thực tập sinh quản lý dự án',
        responsibilities: 'Theo dõi tiến độ dự án, báo cáo tiến độ cho quản lý dự án và tham gia các cuộc họp Scrum hàng ngày.',
        technology: 'Salesforce, Jira, Confluence',
      },
      {
        id: 2,
        nameProject: 'Ứng dụng Quản lý Công việc',
        startTime: '2022-03-01',
        endTime: '2022-05-30',
        client: 'Công ty XYZ',
        description: 'Phát triển ứng dụng quản lý công việc cho doanh nghiệp giúp tối ưu hóa quy trình làm việc và tăng năng suất.',
        members: 'Nhóm 5 thành viên',
        position: 'Thực tập sinh quản lý dự án',
        responsibilities: 'Lập kế hoạch dự án, điều phối công việc, và tổ chức các cuộc họp Sprint Planning và Sprint Review.',
        technology: 'Trello, MS Project, Slack',
      },
    ],
  },
  {
    id: 22,
    fullName: 'Linh Phạm',
    applicationPosition: 'Thực tập sinh thiết kế UI/UX tại Creative Solutions',
    email: 'linhpham2004@gmail.com',
    phone: '0990123456',
    gender: 'FEMALE',
    dateOB: '2004-04-22',
    city: 'Biên Hòa',
    address: '123 Võ Thị Sáu, Biên Hòa',
    linkedIn: 'linkedin.com/in/linhpham',
    github: 'github.com/linhpham',
    aboutYourself: 'Nhà thiết kế UI/UX sáng tạo với sự tập trung mạnh vào thiết kế lấy người dùng làm trung tâm và giao diện trực quan.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Creative Solutions',
        startWorkingTime: '2023-01-01',
        endWorkingTime: '2023-06-30',
        position: 'Thực tập sinh thiết kế UI/UX',
        jobDetail: 'Hỗ trợ thiết kế giao diện người dùng cho các ứng dụng web và di động, tạo wireframes, prototypes và thiết kế hoàn chỉnh. Tham gia vào các buổi họp đánh giá UX và thu thập phản hồi từ người dùng.',
        technology: 'Figma, Adobe XD, Sketch',
      },
    ],
    mainSkill: 'Thiết kế UI/UX, Figma, Adobe XD',
    skills: 'User Interface Design, User Experience Design, Wireframing, Prototyping, Usability Testing',
    school: 'Đại học Kiến trúc TP.HCM',
    startEdudatiomTime: '2022-09-01',
    endEducationTime: '2026-06-30',
    major: 'Thiết kế đồ họa',
    others: 'Đạt giải Nhì cuộc thi Thiết kế UI/UX toàn quốc năm 2022.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Ứng dụng Quản lý Thời gian',
        startTime: '2022-02-01',
        endTime: '2022-04-30',
        client: 'Công ty ABC',
        description: 'Phát triển giao diện người dùng cho ứng dụng quản lý thời gian, giúp người dùng tổ chức và quản lý thời gian hiệu quả.',
        members: 'Nhóm 4 thành viên',
        position: 'Thiết kế UI',
        responsibilities: 'Thiết kế wireframes, prototypes và giao diện cuối cùng, phối hợp với nhóm phát triển để đảm bảo tính khả dụng và trực quan của ứng dụng.',
        technology: 'Figma, Adobe XD',
      },
      {
        id: 2,
        nameProject: 'Website Thương mại Điện tử',
        startTime: '2023-03-01',
        endTime: '2023-05-30',
        client: 'Công ty XYZ',
        description: 'Thiết kế giao diện người dùng cho website thương mại điện tử, tập trung vào trải nghiệm mua sắm trực tuyến mượt mà và hấp dẫn.',
        members: 'Nhóm 5 thành viên',
        position: 'Thiết kế UX',
        responsibilities: 'Nghiên cứu người dùng, tạo wireframes và prototypes, thực hiện kiểm thử khả dụng và cải tiến thiết kế dựa trên phản hồi.',
        technology: 'Figma, Sketch',
      },
    ],
  },
  {
    id: 23,
    fullName: 'Nam Lê',
    applicationPosition: 'Thực tập sinh phát triển game tại GameStudio',
    email: 'namle2000@gmail.com',
    phone: '0901234567',
    gender: 'MALE',
    dateOB: '2000-12-31',
    city: 'Nha Trang',
    address: '456 Trần Phú, Nha Trang',
    linkedIn: 'linkedin.com/in/namle',
    github: 'github.com/namle',
    aboutYourself: 'Nhà phát triển game với niềm đam mê tạo ra những trải nghiệm chơi game hấp dẫn và cuốn hút.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'GameStudio',
        startWorkingTime: '2023-01-01',
        endWorkingTime: '2023-06-30',
        position: 'Thực tập sinh phát triển game',
        jobDetail: 'Hỗ trợ phát triển các tính năng của game, tối ưu hóa mã nguồn và sửa lỗi. Tham gia vào quá trình thiết kế và triển khai các level game.',
        technology: 'Unity, C#',
      },
    ],
    mainSkill: 'Phát triển game, Unity, C#',
    skills: 'Game Development, Unity, C#, Game Design, Problem Solving',
    school: 'Đại học Công nghệ Thông tin TP.HCM',
    startEdudatiomTime: '2019-09-01',
    endEducationTime: '2023-06-30',
    major: 'Kỹ thuật phần mềm',
    others: 'Tham gia cuộc thi phát triển game toàn quốc và đạt giải Ba năm 2022.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Game Phiêu Lưu',
        startTime: '2022-02-01',
        endTime: '2022-04-30',
        client: 'Công ty ABC',
        description: 'Phát triển một game phiêu lưu với đồ họa 3D và cốt truyện hấp dẫn.',
        members: 'Nhóm 3 thành viên',
        position: 'Lập trình viên',
        responsibilities: 'Thiết kế và lập trình các cơ chế gameplay, tối ưu hóa hiệu suất và đảm bảo tính ổn định của game.',
        technology: 'Unity, C#',
      },
      {
        id: 2,
        nameProject: 'Game Học Tập',
        startTime: '2023-03-01',
        endTime: '2023-05-30',
        client: 'Công ty XYZ',
        description: 'Phát triển một game giáo dục nhằm giúp trẻ em học tiếng Anh qua các hoạt động tương tác.',
        members: 'Nhóm 4 thành viên',
        position: 'Lập trình viên',
        responsibilities: 'Phát triển các mini-game, tích hợp âm thanh và đồ họa, đảm bảo tính giáo dục và giải trí của game.',
        technology: 'Unity, C#',
      },
    ],
  },
  {
    id: 1,
    fullName: 'An Phạm',
    applicationPosition: 'Chuyên viên Marketing tại Công ty ABC',
    email: 'anpham@gmail.com',
    phone: '0901234561',
    gender: 'FEMALE',
    dateOB: '1995-01-15',
    city: 'TP. Hồ Chí Minh',
    address: '123 Lê Lợi, Quận 1, TP. Hồ Chí Minh',
    linkedIn: 'linkedin.com/in/anpham',
    github: '',
    aboutYourself: 'Chuyên viên Marketing với kinh nghiệm trong việc lập kế hoạch và triển khai các chiến dịch marketing.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Công ty ABC',
        startWorkingTime: '2021-03-01',
        endWorkingTime: '2023-04-30',
        position: 'Chuyên viên Marketing',
        jobDetail: 'Lập kế hoạch và triển khai các chiến dịch marketing, phân tích dữ liệu và đánh giá hiệu quả.',
        technology: 'Google Analytics, Facebook Ads',
      },
    ],
    mainSkill: 'Marketing, Digital Marketing, Content Creation',
    skills: 'SEO, SEM, Social Media Marketing, Content Creation',
    school: 'Đại học Kinh tế TP.HCM',
    startEdudatiomTime: '2013-09-01',
    endEducationTime: '2017-06-30',
    major: 'Marketing',
    others: 'Tham gia cuộc thi Marketing Quốc gia và đạt giải Nhì năm 2021.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Chiến dịch mùa hè',
        startTime: '2022-05-01',
        endTime: '2022-08-30',
        client: 'Công ty XYZ',
        description: 'Triển khai chiến dịch marketing mùa hè với mục tiêu tăng 20% doanh số.',
        members: 'Nhóm 5 thành viên',
        position: 'Trưởng nhóm',
        responsibilities: 'Lập kế hoạch, quản lý ngân sách và đánh giá hiệu quả chiến dịch.',
        technology: 'Google Analytics, Facebook Ads',
      },
    ],
  },
  {
    id: 2,
    fullName: 'Bình Trần',
    applicationPosition: 'Kỹ sư Cơ khí tại Công ty DEF',
    email: 'binhtran@gmail.com',
    phone: '0901234562',
    gender: 'MALE',
    dateOB: '1992-05-20',
    city: 'TP. Hồ Chí Minh',
    address: '456 Nguyễn Thị Minh Khai, Quận 3, TP. Hồ Chí Minh',
    linkedIn: 'linkedin.com/in/binhtran',
    github: '',
    aboutYourself: 'Kỹ sư Cơ khí với kinh nghiệm thiết kế và phát triển các sản phẩm cơ khí.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Công ty DEF',
        startWorkingTime: '2018-01-01',
        endWorkingTime: '2023-04-30',
        position: 'Kỹ sư Cơ khí',
        jobDetail: 'Thiết kế và phát triển các sản phẩm cơ khí, giám sát quy trình sản xuất.',
        technology: 'AutoCAD, SolidWorks',
      },
    ],
    mainSkill: 'Mechanical Engineering, CAD, CAM',
    skills: 'AutoCAD, SolidWorks, CNC Machining, Product Development',
    school: 'Đại học Bách Khoa TP.HCM',
    startEdudatiomTime: '2010-09-01',
    endEducationTime: '2014-06-30',
    major: 'Kỹ thuật Cơ khí',
    others: 'Đạt giải Nhất cuộc thi Sáng tạo Cơ khí TP.HCM năm 2019.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Dự án thiết kế máy CNC',
        startTime: '2021-01-01',
        endTime: '2021-12-31',
        client: 'Công ty GHI',
        description: 'Thiết kế và phát triển máy CNC cho công ty GHI.',
        members: 'Nhóm 4 thành viên',
        position: 'Trưởng nhóm',
        responsibilities: 'Thiết kế, lập trình và kiểm tra chất lượng sản phẩm.',
        technology: 'AutoCAD, SolidWorks',
      },
    ],
  },
  {
    id: 3,
    fullName: 'Cúc Nguyễn',
    applicationPosition: 'Nhân viên Kế toán tại Công ty JKL',
    email: 'cucnguyen@gmail.com',
    phone: '0901234563',
    gender: 'FEMALE',
    dateOB: '1988-11-12',
    city: 'TP. Hồ Chí Minh',
    address: '789 Pasteur, Quận 3, TP. Hồ Chí Minh',
    linkedIn: 'linkedin.com/in/cucnguyen',
    github: '',
    aboutYourself: 'Nhân viên Kế toán với hơn 10 năm kinh nghiệm trong việc quản lý tài chính và kế toán doanh nghiệp.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Công ty JKL',
        startWorkingTime: '2012-02-01',
        endWorkingTime: '2023-04-30',
        position: 'Nhân viên Kế toán',
        jobDetail: 'Quản lý tài chính, lập báo cáo tài chính và đảm bảo tuân thủ quy định kế toán.',
        technology: 'SAP, Excel',
      },
    ],
    mainSkill: 'Accounting, Financial Management, Taxation',
    skills: 'Financial Reporting, SAP, Excel, Tax Compliance',
    school: 'Đại học Kinh tế TP.HCM',
    startEdudatiomTime: '2006-09-01',
    endEducationTime: '2010-06-30',
    major: 'Kế toán',
    others: 'Đạt chứng chỉ ACCA năm 2015.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Dự án cải tiến quy trình kế toán',
        startTime: '2020-01-01',
        endTime: '2020-12-31',
        client: 'Công ty MNO',
        description: 'Cải tiến quy trình kế toán để nâng cao hiệu quả và giảm chi phí.',
        members: 'Nhóm 3 thành viên',
        position: 'Trưởng nhóm',
        responsibilities: 'Lập kế hoạch, triển khai và đánh giá kết quả cải tiến.',
        technology: 'SAP, Excel',
      },
    ],
  },
  {
    id: 4,
    fullName: 'Dũng Võ',
    applicationPosition: 'Chuyên viên Nhân sự tại Công ty PQR',
    email: 'dungvo@gmail.com',
    phone: '0901234564',
    gender: 'MALE',
    dateOB: '1990-06-25',
    city: 'TP. Hồ Chí Minh',
    address: '123 Đinh Tiên Hoàng, Quận Bình Thạnh, TP. Hồ Chí Minh',
    linkedIn: 'linkedin.com/in/dungvo',
    github: '',
    aboutYourself: 'Chuyên viên Nhân sự với kinh nghiệm trong việc tuyển dụng và quản lý nhân sự.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Công ty PQR',
        startWorkingTime: '2015-04-01',
        endWorkingTime: '2023-04-30',
        position: 'Chuyên viên Nhân sự',
        jobDetail: 'Tuyển dụng, đào tạo và quản lý nhân sự, xây dựng chính sách nhân sự.',
        technology: 'HRIS, Excel',
      },
    ],
    mainSkill: 'Human Resources, Recruitment, Training',
    skills: 'Recruitment, Training and Development, Employee Relations, HRIS',
    school: 'Đại học Kinh tế TP.HCM',
    startEdudatiomTime: '2008-09-01',
    endEducationTime: '2012-06-30',
    major: 'Quản trị Nhân sự',
    others: 'Đạt chứng chỉ PHR năm 2018.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Dự án cải tiến quy trình tuyển dụng',
        startTime: '2021-05-01',
        endTime: '2021-12-31',
        client: 'Công ty STU',
        description: 'Cải tiến quy trình tuyển dụng để tăng hiệu quả tuyển dụng và giảm thời gian tuyển dụng.',
        members: 'Nhóm 4 thành viên',
        position: 'Trưởng nhóm',
        responsibilities: 'Lập kế hoạch, triển khai và đánh giá kết quả cải tiến.',
        technology: 'HRIS, Excel',
      },
    ],
  },
  {
    id: 5,
    fullName: 'Em Mai',
    applicationPosition: 'Nhân viên Phục vụ tại Nhà hàng 5 Sao',
    email: 'emmai@gmail.com',
    phone: '0901234565',
    gender: 'FEMALE',
    dateOB: '1998-03-10',
    city: 'TP. Hồ Chí Minh',
    address: '789 Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh',
    linkedIn: 'linkedin.com/in/emmai',
    github: '',
    aboutYourself: 'Nhân viên Phục vụ tận tâm với kinh nghiệm trong việc đảm bảo sự hài lòng của khách hàng.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Nhà hàng 5 Sao',
        startWorkingTime: '2020-06-01',
        endWorkingTime: '2023-04-30',
        position: 'Nhân viên Phục vụ',
        jobDetail: 'Phục vụ khách hàng, đảm bảo sự hài lòng của khách hàng và hỗ trợ các hoạt động của nhà hàng.',
        technology: '',
      },
    ],
    mainSkill: 'Customer Service, Food and Beverage Service',
    skills: 'Customer Service, Teamwork, Communication, Problem Solving',
    school: 'Trường Cao đẳng Du lịch Sài Gòn',
    startEdudatiomTime: '2016-09-01',
    endEducationTime: '2019-06-30',
    major: 'Quản trị Nhà hàng Khách sạn',
    others: 'Đạt giải Nhì cuộc thi Nhân viên Phục vụ xuất sắc năm 2021.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Dự án nâng cao chất lượng phục vụ',
        startTime: '2022-01-01',
        endTime: '2022-12-31',
        client: 'Nhà hàng 5 Sao',
        description: 'Nâng cao chất lượng phục vụ để tăng sự hài lòng của khách hàng.',
        members: 'Nhóm 3 thành viên',
        position: 'Trưởng nhóm',
        responsibilities: 'Đánh giá hiện trạng, đề xuất cải tiến và triển khai thực hiện.',
        technology: '',
      },
    ],
  },
  {
    id: 6,
    fullName: 'Giai Vũ',
    applicationPosition: 'Nhân viên Bán hàng tại Siêu thị XYZ',
    email: 'giaivu@gmail.com',
    phone: '0901234566',
    gender: 'MALE',
    dateOB: '1993-08-15',
    city: 'TP. Hồ Chí Minh',
    address: '123 Tôn Đức Thắng, Quận 1, TP. Hồ Chí Minh',
    linkedIn: 'linkedin.com/in/giaivu',
    github: '',
    aboutYourself: 'Nhân viên Bán hàng với kỹ năng giao tiếp tốt và khả năng thuyết phục khách hàng.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Siêu thị XYZ',
        startWorkingTime: '2019-03-01',
        endWorkingTime: '2023-04-30',
        position: 'Nhân viên Bán hàng',
        jobDetail: 'Tư vấn và bán hàng, giải quyết các vấn đề của khách hàng và hỗ trợ quản lý hàng hóa.',
        technology: '',
      },
    ],
    mainSkill: 'Sales, Customer Service, Product Knowledge',
    skills: 'Sales, Communication, Customer Service, Inventory Management',
    school: 'Trường Cao đẳng Kinh tế Đối ngoại',
    startEdudatiomTime: '2011-09-01',
    endEducationTime: '2014-06-30',
    major: 'Quản trị Kinh doanh',
    others: 'Đạt giải Nhất cuộc thi Nhân viên Bán hàng xuất sắc năm 2020.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Dự án tăng doanh số bán hàng',
        startTime: '2021-01-01',
        endTime: '2021-12-31',
        client: 'Siêu thị XYZ',
        description: 'Tăng doanh số bán hàng thông qua các chiến lược bán hàng hiệu quả.',
        members: 'Nhóm 4 thành viên',
        position: 'Trưởng nhóm',
        responsibilities: 'Lập kế hoạch, triển khai và đánh giá kết quả dự án.',
        technology: '',
      },
    ],
  },
  {
    id: 7,
    fullName: 'Hạnh Đặng',
    applicationPosition: 'Nhân viên Hành chính tại Công ty KLM',
    email: 'hanhdang@gmail.com',
    phone: '0901234567',
    gender: 'FEMALE',
    dateOB: '1987-04-20',
    city: 'TP. Hồ Chí Minh',
    address: '456 Lê Văn Sỹ, Quận 3, TP. Hồ Chí Minh',
    linkedIn: 'linkedin.com/in/hanhdang',
    github: '',
    aboutYourself: 'Nhân viên Hành chính với kỹ năng tổ chức và quản lý tài liệu xuất sắc.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Công ty KLM',
        startWorkingTime: '2010-05-01',
        endWorkingTime: '2023-04-30',
        position: 'Nhân viên Hành chính',
        jobDetail: 'Quản lý tài liệu, hỗ trợ các hoạt động hành chính và đảm bảo vận hành văn phòng suôn sẻ.',
        technology: 'MS Office',
      },
    ],
    mainSkill: 'Administrative Support, Document Management',
    skills: 'Organizational Skills, Communication, MS Office, Time Management',
    school: 'Đại học Khoa học Xã hội và Nhân văn TP.HCM',
    startEdudatiomTime: '2005-09-01',
    endEducationTime: '2009-06-30',
    major: 'Quản trị Văn phòng',
    others: 'Đạt chứng chỉ Quản trị Hành chính Văn phòng năm 2013.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Dự án số hóa tài liệu',
        startTime: '2022-01-01',
        endTime: '2022-12-31',
        client: 'Công ty KLM',
        description: 'Số hóa toàn bộ tài liệu của công ty để tăng hiệu quả quản lý và truy xuất tài liệu.',
        members: 'Nhóm 3 thành viên',
        position: 'Trưởng nhóm',
        responsibilities: 'Lập kế hoạch, triển khai và đánh giá kết quả dự án.',
        technology: 'MS Office',
      },
    ],
  },
  {
    id: 8,
    fullName: 'Khánh Nguyễn',
    applicationPosition: 'Nhân viên IT tại Công ty NOP',
    email: 'khanhnguyen@gmail.com',
    phone: '0901234568',
    gender: 'MALE',
    dateOB: '1995-07-10',
    city: 'TP. Hồ Chí Minh',
    address: '123 Phan Đăng Lưu, Quận Phú Nhuận, TP. Hồ Chí Minh',
    linkedIn: 'linkedin.com/in/khanhnguyen',
    github: 'github.com/khanhnguyen',
    aboutYourself: 'Nhân viên IT với kinh nghiệm trong việc quản lý hệ thống và hỗ trợ kỹ thuật.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Công ty NOP',
        startWorkingTime: '2017-09-01',
        endWorkingTime: '2023-04-30',
        position: 'Nhân viên IT',
        jobDetail: 'Quản lý hệ thống, hỗ trợ người dùng và xử lý các vấn đề kỹ thuật.',
        technology: 'Windows Server, Linux, Cisco',
      },
    ],
    mainSkill: 'System Administration, Network Management',
    skills: 'Windows Server, Linux, Cisco, Technical Support',
    school: 'Đại học Công nghệ Thông tin TP.HCM',
    startEdudatiomTime: '2013-09-01',
    endEducationTime: '2017-06-30',
    major: 'Công nghệ Thông tin',
    others: 'Đạt chứng chỉ CCNA năm 2019.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Dự án nâng cấp hệ thống mạng',
        startTime: '2020-05-01',
        endTime: '2020-12-31',
        client: 'Công ty NOP',
        description: 'Nâng cấp hệ thống mạng của công ty để tăng cường hiệu quả và bảo mật.',
        members: 'Nhóm 4 thành viên',
        position: 'Trưởng nhóm',
        responsibilities: 'Lập kế hoạch, triển khai và đánh giá kết quả dự án.',
        technology: 'Cisco, Windows Server, Linux',
      },
    ],
  },
  {
    id: 9,
    fullName: 'Lam Trần',
    applicationPosition: 'Giáo viên Tiếng Anh tại Trường Quốc tế ABC',
    email: 'lamtran@gmail.com',
    phone: '0901234569',
    gender: 'FEMALE',
    dateOB: '1985-09-30',
    city: 'TP. Hồ Chí Minh',
    address: '456 Cách Mạng Tháng 8, Quận 10, TP. Hồ Chí Minh',
    linkedIn: 'linkedin.com/in/lamtran',
    github: '',
    aboutYourself: 'Giáo viên Tiếng Anh với kinh nghiệm giảng dạy tại các trường quốc tế và phương pháp dạy học sáng tạo.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Trường Quốc tế ABC',
        startWorkingTime: '2010-01-01',
        endWorkingTime: '2023-04-30',
        position: 'Giáo viên Tiếng Anh',
        jobDetail: 'Giảng dạy tiếng Anh, phát triển giáo trình và đánh giá kết quả học tập của học sinh.',
        technology: 'MS Office, Zoom',
      },
    ],
    mainSkill: 'Teaching, Curriculum Development',
    skills: 'Teaching, Curriculum Development, Communication, Classroom Management',
    school: 'Đại học Sư phạm TP.HCM',
    startEdudatiomTime: '2003-09-01',
    endEducationTime: '2007-06-30',
    major: 'Giảng dạy Tiếng Anh',
    others: 'Đạt chứng chỉ TESOL năm 2015.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Dự án cải tiến phương pháp giảng dạy',
        startTime: '2021-01-01',
        endTime: '2021-12-31',
        client: 'Trường Quốc tế ABC',
        description: 'Cải tiến phương pháp giảng dạy để nâng cao hiệu quả học tập của học sinh.',
        members: 'Nhóm 5 thành viên',
        position: 'Trưởng nhóm',
        responsibilities: 'Nghiên cứu, đề xuất và triển khai các phương pháp giảng dạy mới.',
        technology: 'MS Office, Zoom',
      },
    ],
  },
  {
    id: 10,
    fullName: 'Minh Lê',
    applicationPosition: 'Chuyên viên Thiết kế Đồ họa tại Công ty RST',
    email: 'minhle@gmail.com',
    phone: '0901234570',
    gender: 'MALE',
    dateOB: '1997-12-15',
    city: 'TP. Hồ Chí Minh',
    address: '789 Điện Biên Phủ, Quận Bình Thạnh, TP. Hồ Chí Minh',
    linkedIn: 'linkedin.com/in/minhle',
    github: '',
    aboutYourself: 'Chuyên viên Thiết kế Đồ họa với khả năng sáng tạo và kinh nghiệm trong việc thiết kế các sản phẩm đồ họa.',
    workingExperiences: [
      {
        id: 1,
        companyName: 'Công ty RST',
        startWorkingTime: '2019-05-01',
        endWorkingTime: '2023-04-30',
        position: 'Chuyên viên Thiết kế Đồ họa',
        jobDetail: 'Thiết kế các sản phẩm đồ họa, quản lý dự án thiết kế và làm việc với khách hàng.',
        technology: 'Adobe Photoshop, Illustrator',
      },
    ],
    mainSkill: 'Graphic Design, Adobe Creative Suite',
    skills: 'Graphic Design, Adobe Photoshop, Adobe Illustrator, Creativity',
    school: 'Đại học Mỹ thuật TP.HCM',
    startEdudatiomTime: '2015-09-01',
    endEducationTime: '2019-06-30',
    major: 'Thiết kế Đồ họa',
    others: 'Đạt giải Nhất cuộc thi Thiết kế Đồ họa TP.HCM năm 2020.',
    workingProjects: [
      {
        id: 1,
        nameProject: 'Dự án thiết kế bộ nhận diện thương hiệu',
        startTime: '2022-01-01',
        endTime: '2022-12-31',
        client: 'Công ty UVW',
        description: 'Thiết kế bộ nhận diện thương hiệu cho công ty UVW.',
        members: 'Nhóm 3 thành viên',
        position: 'Trưởng nhóm',
        responsibilities: 'Lập kế hoạch, thiết kế và đánh giá kết quả dự án.',
        technology: 'Adobe Photoshop, Illustrator',
      },
    ],
  },
]
