export const ROOM_REQUERST = "ROOM_REQUERST";
export const ROOM_SUCCESS = "ROOM_SUCCESS";
export const ROOM_ERROR = "ROOM_ERROR";


export const ROOM_IDJOB_REQUERST = "ROOM_IDJOB_REQUERST";
export const ROOM_IDJOB_SUCCESS = "ROOM_IDJOB_SUCCESS";
export const ROOM_IDJOB_ERROR = "ROOM_IDJOB_ERROR";