version: '3.8'
services:
  # panda-frontend:
  #   build:
  #     context: ../../Front-end
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - panda-backend
  #   volumes:
  #     - webdata-panda:/build
  #   networks:
  #     - panda_network

  panda-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=panda
      - MYSQL_ROOT_PASSWORD=nguyenkhanh2kpi
    ports:
      - 10051:3306
    expose:
      - 3306
    networks:
      - panda_network
    container_name: panda-mysql
    
  panda-backend:
    build:
      context: ../../Back_end
      dockerfile: Dockerfile
    container_name: panda-backend-container
    depends_on:
      - panda-db
    restart: unless-stopped
    ports:
      - 9090:8080
    environment:
      spring.datasource.url: jdbc:mysql://panda-db:3306/panda
      spring.datasource.username: root
      spring.datasource.password: nguyenkhanh2kpi
      server.servlet.context-path: /api
    networks:
      - panda_network
    expose:
      - 8080
    image: panda-backend


  panda-nginx:
    image: nginx:1.23.3
    build: 
      context: .
    container_name: panda-nginx
    ports:
      - 10046:80
    volumes:
      - ../../Front-end/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # - webdata-panda:/usr/share/nginx/html
    depends_on:
      - panda-db
      - panda-backend
      # - panda-frontend
    networks:
      - panda_network


volumes:
  webdata-panda:

networks:
  panda_network:
    driver: bridge


