#version: 2.1
#executors:
#  java17:
#    docker:
#      - image: 'cimg/openjdk:17.0'
#orbs:
#  maven: circleci/maven@1.3.0
#workflows:
#  maven_test:
#    jobs:
#      - maven/test:
#          command: 'test'
#          executor: java17


version: 2.1
executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'
orbs:
  maven: circleci/maven@1.3.0
workflows:
  maven_test:
    jobs:
      - maven/test:
          command: 'test'
          executor: java17
          test_results_path: ./test.yml
